<template>
  <section class="card">
    <h2>Project Modules</h2>
    <p>Use this app to practice algorithm explanations, system design sketching, and English interview Q&A.</p>
    <ul>
      <li>LeetCode AI analysis with code + complexity explanation.</li>
      <li>System design draft canvas data save.</li>
      <li>English interview questions generated by AI.</li>
    </ul>
  </section>

  <section class="card">
    <h3>App Settings</h3>
    <label>appId (must stay string)</label>
    <div class="row">
      <input v-model="localAppId" placeholder="interview-coach-web" />
      <button @click="saveAppId">Save</button>
    </div>
    <small>Current appId: {{ appStore.appId }}</small>
  </section>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useAppStore } from "../stores/app";

const appStore = useAppStore();
const localAppId = ref(appStore.appId);

function saveAppId() {
  appStore.setAppId(localAppId.value);
}
</script>
